# Generated by Django 4.0.2 on 2022-02-12 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='liked',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
