# Generated by Django 4.0.1 on 2022-01-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_student_last_updated_date_student_register_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year_im_school',
            new_name='year_in_school',
        ),
    ]
